---
name: release

on: 
  push:
    branches:
      - main

jobs:
  release-on-push:
    runs-on: [small, telia-managed, Linux, X64]
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - id: release
        uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor
          tag_prefix: v
